name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: robin
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/html/dailyexpensetracker/backend
            git pull origin main
            # Example: Restart a service
            sudo systemctl restart apache2
            # Example: Run migrations
            php artisan migrate
            # Example: Clear cache
            php artisan cache:clear
            # Example: Install dependencies
            composer install
            # Example: Generate assets
            cd /var/www/html/dailyexpensetracker/backend/frontend
            npm install
            npm run build